// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package kinesisvideomediacounter

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/kinesisvideomedia"
)

// GetMediaRequest is a passthrough to the underlying GetMediaRequest.
// It will increment the count of requests made to GetMedia.
func (c *KinesisVideoMedia) GetMediaRequest(input *kinesisvideomedia.GetMediaInput) (req *request.Request, output *kinesisvideomedia.GetMediaOutput) {
	c.inc("GetMedia")
	return c.svc.GetMediaRequest(input)
}

// GetMedia is a passthrough to the underlying GetMedia method.
// It will increment the count of requests made to GetMedia.
func (c *KinesisVideoMedia) GetMedia(input *kinesisvideomedia.GetMediaInput) (*kinesisvideomedia.GetMediaOutput, error) {
	c.inc("GetMedia")
	return c.svc.GetMedia(input)
}

// GetMediaWithContext is a passthrough to the underlying GetMediaWithContext method.
// It will increment the count of requests made to GetMedia.
func (c *KinesisVideoMedia) GetMediaWithContext(ctx aws.Context, input *kinesisvideomedia.GetMediaInput, opts ...request.Option) (*kinesisvideomedia.GetMediaOutput, error) {
	c.inc("GetMedia")
	return c.svc.GetMediaWithContext(ctx, input, opts...)
}
