// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package wafregionalcounter

import (
	"sync"
	"sync/atomic"

	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/wafregional/wafregionaliface"
)

// WAFRegional counts the API operations made to AWS WAF Regional.
type WAFRegional struct {
	svc    wafregionaliface.WAFRegionalAPI
	counts sync.Map
}

var _ wafregionaliface.WAFRegionalAPI = &WAFRegional{}

// New creates a new instance of the WAFRegional counter.
func New(svc wafregionaliface.WAFRegionalAPI) *WAFRegional {
	return &WAFRegional{svc: svc}
}

// Counters returns a snapshot of current counter values for each API operation.
func (c *WAFRegional) Counters() map[string]int64 {
	counters := map[string]int64{}
	c.counts.Range(func(key, value interface{}) bool {
		counters[key.(string)] = value.(*counter).count()
		return true
	})
	return counters
}

// incViaRequestOption returns a request.Option that increments the given op.
func (c *WAFRegional) incViaRequestOption(op string) request.Option {
	return func(*request.Request) {
		c.inc(op)
	}
}

// inc increments the counter for the operation by 1.
func (c *WAFRegional) inc(op string) {
	cnt, _ := c.counts.LoadOrStore(op, &counter{})
	cnt.(*counter).inc()
}

// count returns the current counter value for the operation.
func (c *WAFRegional) count(op string) int64 {
	cnt, _ := c.counts.LoadOrStore(op, &counter{})
	return cnt.(*counter).count()
}

// counter is a threadsafe cumulative counter.
type counter struct {
	c int64
}

// count returns the current count.
func (c *counter) count() int64 {
	return atomic.LoadInt64(&c.c)
}

// inc increments the counter by one.
func (c *counter) inc() {
	atomic.AddInt64(&c.c, 1)
}
