// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package elastictranscodercounter

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/elastictranscoder"
)

// WaitUntilJobComplete calls WaitUntilJobCompleteWithContext with aws.BackgroundContext().
func (c *ElasticTranscoder) WaitUntilJobComplete(input *elastictranscoder.ReadJobInput) error {
	return c.WaitUntilJobCompleteWithContext(aws.BackgroundContext(), input)
}

// WaitUntilJobCompleteWithContext calls the underlying client method with a request option that
// will count ReadJob requests.
func (c *ElasticTranscoder) WaitUntilJobCompleteWithContext(ctx aws.Context, input *elastictranscoder.ReadJobInput, opts ...request.WaiterOption) error {
	opts = append(opts, request.WithWaiterRequestOptions(c.incViaRequestOption("ReadJob")))
	return c.svc.WaitUntilJobCompleteWithContext(ctx, input, opts...)
}
