// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package cloudhsmcounter

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/cloudhsm"
)

// AddTagsToResourceRequest is a passthrough to the underlying AddTagsToResourceRequest.
// It will increment the count of requests made to AddTagsToResource.
func (c *CloudHSM) AddTagsToResourceRequest(input *cloudhsm.AddTagsToResourceInput) (req *request.Request, output *cloudhsm.AddTagsToResourceOutput) {
	c.inc("AddTagsToResource")
	return c.svc.AddTagsToResourceRequest(input)
}

// AddTagsToResource is a passthrough to the underlying AddTagsToResource method.
// It will increment the count of requests made to AddTagsToResource.
func (c *CloudHSM) AddTagsToResource(input *cloudhsm.AddTagsToResourceInput) (*cloudhsm.AddTagsToResourceOutput, error) {
	c.inc("AddTagsToResource")
	return c.svc.AddTagsToResource(input)
}

// AddTagsToResourceWithContext is a passthrough to the underlying AddTagsToResourceWithContext method.
// It will increment the count of requests made to AddTagsToResource.
func (c *CloudHSM) AddTagsToResourceWithContext(ctx aws.Context, input *cloudhsm.AddTagsToResourceInput, opts ...request.Option) (*cloudhsm.AddTagsToResourceOutput, error) {
	c.inc("AddTagsToResource")
	return c.svc.AddTagsToResourceWithContext(ctx, input, opts...)
}

// CreateHapgRequest is a passthrough to the underlying CreateHapgRequest.
// It will increment the count of requests made to CreateHapg.
func (c *CloudHSM) CreateHapgRequest(input *cloudhsm.CreateHapgInput) (req *request.Request, output *cloudhsm.CreateHapgOutput) {
	c.inc("CreateHapg")
	return c.svc.CreateHapgRequest(input)
}

// CreateHapg is a passthrough to the underlying CreateHapg method.
// It will increment the count of requests made to CreateHapg.
func (c *CloudHSM) CreateHapg(input *cloudhsm.CreateHapgInput) (*cloudhsm.CreateHapgOutput, error) {
	c.inc("CreateHapg")
	return c.svc.CreateHapg(input)
}

// CreateHapgWithContext is a passthrough to the underlying CreateHapgWithContext method.
// It will increment the count of requests made to CreateHapg.
func (c *CloudHSM) CreateHapgWithContext(ctx aws.Context, input *cloudhsm.CreateHapgInput, opts ...request.Option) (*cloudhsm.CreateHapgOutput, error) {
	c.inc("CreateHapg")
	return c.svc.CreateHapgWithContext(ctx, input, opts...)
}

// CreateHsmRequest is a passthrough to the underlying CreateHsmRequest.
// It will increment the count of requests made to CreateHsm.
func (c *CloudHSM) CreateHsmRequest(input *cloudhsm.CreateHsmInput) (req *request.Request, output *cloudhsm.CreateHsmOutput) {
	c.inc("CreateHsm")
	return c.svc.CreateHsmRequest(input)
}

// CreateHsm is a passthrough to the underlying CreateHsm method.
// It will increment the count of requests made to CreateHsm.
func (c *CloudHSM) CreateHsm(input *cloudhsm.CreateHsmInput) (*cloudhsm.CreateHsmOutput, error) {
	c.inc("CreateHsm")
	return c.svc.CreateHsm(input)
}

// CreateHsmWithContext is a passthrough to the underlying CreateHsmWithContext method.
// It will increment the count of requests made to CreateHsm.
func (c *CloudHSM) CreateHsmWithContext(ctx aws.Context, input *cloudhsm.CreateHsmInput, opts ...request.Option) (*cloudhsm.CreateHsmOutput, error) {
	c.inc("CreateHsm")
	return c.svc.CreateHsmWithContext(ctx, input, opts...)
}

// CreateLunaClientRequest is a passthrough to the underlying CreateLunaClientRequest.
// It will increment the count of requests made to CreateLunaClient.
func (c *CloudHSM) CreateLunaClientRequest(input *cloudhsm.CreateLunaClientInput) (req *request.Request, output *cloudhsm.CreateLunaClientOutput) {
	c.inc("CreateLunaClient")
	return c.svc.CreateLunaClientRequest(input)
}

// CreateLunaClient is a passthrough to the underlying CreateLunaClient method.
// It will increment the count of requests made to CreateLunaClient.
func (c *CloudHSM) CreateLunaClient(input *cloudhsm.CreateLunaClientInput) (*cloudhsm.CreateLunaClientOutput, error) {
	c.inc("CreateLunaClient")
	return c.svc.CreateLunaClient(input)
}

// CreateLunaClientWithContext is a passthrough to the underlying CreateLunaClientWithContext method.
// It will increment the count of requests made to CreateLunaClient.
func (c *CloudHSM) CreateLunaClientWithContext(ctx aws.Context, input *cloudhsm.CreateLunaClientInput, opts ...request.Option) (*cloudhsm.CreateLunaClientOutput, error) {
	c.inc("CreateLunaClient")
	return c.svc.CreateLunaClientWithContext(ctx, input, opts...)
}

// DeleteHapgRequest is a passthrough to the underlying DeleteHapgRequest.
// It will increment the count of requests made to DeleteHapg.
func (c *CloudHSM) DeleteHapgRequest(input *cloudhsm.DeleteHapgInput) (req *request.Request, output *cloudhsm.DeleteHapgOutput) {
	c.inc("DeleteHapg")
	return c.svc.DeleteHapgRequest(input)
}

// DeleteHapg is a passthrough to the underlying DeleteHapg method.
// It will increment the count of requests made to DeleteHapg.
func (c *CloudHSM) DeleteHapg(input *cloudhsm.DeleteHapgInput) (*cloudhsm.DeleteHapgOutput, error) {
	c.inc("DeleteHapg")
	return c.svc.DeleteHapg(input)
}

// DeleteHapgWithContext is a passthrough to the underlying DeleteHapgWithContext method.
// It will increment the count of requests made to DeleteHapg.
func (c *CloudHSM) DeleteHapgWithContext(ctx aws.Context, input *cloudhsm.DeleteHapgInput, opts ...request.Option) (*cloudhsm.DeleteHapgOutput, error) {
	c.inc("DeleteHapg")
	return c.svc.DeleteHapgWithContext(ctx, input, opts...)
}

// DeleteHsmRequest is a passthrough to the underlying DeleteHsmRequest.
// It will increment the count of requests made to DeleteHsm.
func (c *CloudHSM) DeleteHsmRequest(input *cloudhsm.DeleteHsmInput) (req *request.Request, output *cloudhsm.DeleteHsmOutput) {
	c.inc("DeleteHsm")
	return c.svc.DeleteHsmRequest(input)
}

// DeleteHsm is a passthrough to the underlying DeleteHsm method.
// It will increment the count of requests made to DeleteHsm.
func (c *CloudHSM) DeleteHsm(input *cloudhsm.DeleteHsmInput) (*cloudhsm.DeleteHsmOutput, error) {
	c.inc("DeleteHsm")
	return c.svc.DeleteHsm(input)
}

// DeleteHsmWithContext is a passthrough to the underlying DeleteHsmWithContext method.
// It will increment the count of requests made to DeleteHsm.
func (c *CloudHSM) DeleteHsmWithContext(ctx aws.Context, input *cloudhsm.DeleteHsmInput, opts ...request.Option) (*cloudhsm.DeleteHsmOutput, error) {
	c.inc("DeleteHsm")
	return c.svc.DeleteHsmWithContext(ctx, input, opts...)
}

// DeleteLunaClientRequest is a passthrough to the underlying DeleteLunaClientRequest.
// It will increment the count of requests made to DeleteLunaClient.
func (c *CloudHSM) DeleteLunaClientRequest(input *cloudhsm.DeleteLunaClientInput) (req *request.Request, output *cloudhsm.DeleteLunaClientOutput) {
	c.inc("DeleteLunaClient")
	return c.svc.DeleteLunaClientRequest(input)
}

// DeleteLunaClient is a passthrough to the underlying DeleteLunaClient method.
// It will increment the count of requests made to DeleteLunaClient.
func (c *CloudHSM) DeleteLunaClient(input *cloudhsm.DeleteLunaClientInput) (*cloudhsm.DeleteLunaClientOutput, error) {
	c.inc("DeleteLunaClient")
	return c.svc.DeleteLunaClient(input)
}

// DeleteLunaClientWithContext is a passthrough to the underlying DeleteLunaClientWithContext method.
// It will increment the count of requests made to DeleteLunaClient.
func (c *CloudHSM) DeleteLunaClientWithContext(ctx aws.Context, input *cloudhsm.DeleteLunaClientInput, opts ...request.Option) (*cloudhsm.DeleteLunaClientOutput, error) {
	c.inc("DeleteLunaClient")
	return c.svc.DeleteLunaClientWithContext(ctx, input, opts...)
}

// DescribeHapgRequest is a passthrough to the underlying DescribeHapgRequest.
// It will increment the count of requests made to DescribeHapg.
func (c *CloudHSM) DescribeHapgRequest(input *cloudhsm.DescribeHapgInput) (req *request.Request, output *cloudhsm.DescribeHapgOutput) {
	c.inc("DescribeHapg")
	return c.svc.DescribeHapgRequest(input)
}

// DescribeHapg is a passthrough to the underlying DescribeHapg method.
// It will increment the count of requests made to DescribeHapg.
func (c *CloudHSM) DescribeHapg(input *cloudhsm.DescribeHapgInput) (*cloudhsm.DescribeHapgOutput, error) {
	c.inc("DescribeHapg")
	return c.svc.DescribeHapg(input)
}

// DescribeHapgWithContext is a passthrough to the underlying DescribeHapgWithContext method.
// It will increment the count of requests made to DescribeHapg.
func (c *CloudHSM) DescribeHapgWithContext(ctx aws.Context, input *cloudhsm.DescribeHapgInput, opts ...request.Option) (*cloudhsm.DescribeHapgOutput, error) {
	c.inc("DescribeHapg")
	return c.svc.DescribeHapgWithContext(ctx, input, opts...)
}

// DescribeHsmRequest is a passthrough to the underlying DescribeHsmRequest.
// It will increment the count of requests made to DescribeHsm.
func (c *CloudHSM) DescribeHsmRequest(input *cloudhsm.DescribeHsmInput) (req *request.Request, output *cloudhsm.DescribeHsmOutput) {
	c.inc("DescribeHsm")
	return c.svc.DescribeHsmRequest(input)
}

// DescribeHsm is a passthrough to the underlying DescribeHsm method.
// It will increment the count of requests made to DescribeHsm.
func (c *CloudHSM) DescribeHsm(input *cloudhsm.DescribeHsmInput) (*cloudhsm.DescribeHsmOutput, error) {
	c.inc("DescribeHsm")
	return c.svc.DescribeHsm(input)
}

// DescribeHsmWithContext is a passthrough to the underlying DescribeHsmWithContext method.
// It will increment the count of requests made to DescribeHsm.
func (c *CloudHSM) DescribeHsmWithContext(ctx aws.Context, input *cloudhsm.DescribeHsmInput, opts ...request.Option) (*cloudhsm.DescribeHsmOutput, error) {
	c.inc("DescribeHsm")
	return c.svc.DescribeHsmWithContext(ctx, input, opts...)
}

// DescribeLunaClientRequest is a passthrough to the underlying DescribeLunaClientRequest.
// It will increment the count of requests made to DescribeLunaClient.
func (c *CloudHSM) DescribeLunaClientRequest(input *cloudhsm.DescribeLunaClientInput) (req *request.Request, output *cloudhsm.DescribeLunaClientOutput) {
	c.inc("DescribeLunaClient")
	return c.svc.DescribeLunaClientRequest(input)
}

// DescribeLunaClient is a passthrough to the underlying DescribeLunaClient method.
// It will increment the count of requests made to DescribeLunaClient.
func (c *CloudHSM) DescribeLunaClient(input *cloudhsm.DescribeLunaClientInput) (*cloudhsm.DescribeLunaClientOutput, error) {
	c.inc("DescribeLunaClient")
	return c.svc.DescribeLunaClient(input)
}

// DescribeLunaClientWithContext is a passthrough to the underlying DescribeLunaClientWithContext method.
// It will increment the count of requests made to DescribeLunaClient.
func (c *CloudHSM) DescribeLunaClientWithContext(ctx aws.Context, input *cloudhsm.DescribeLunaClientInput, opts ...request.Option) (*cloudhsm.DescribeLunaClientOutput, error) {
	c.inc("DescribeLunaClient")
	return c.svc.DescribeLunaClientWithContext(ctx, input, opts...)
}

// GetConfigRequest is a passthrough to the underlying GetConfigRequest.
// It will increment the count of requests made to GetConfig.
func (c *CloudHSM) GetConfigRequest(input *cloudhsm.GetConfigInput) (req *request.Request, output *cloudhsm.GetConfigOutput) {
	c.inc("GetConfig")
	return c.svc.GetConfigRequest(input)
}

// GetConfig is a passthrough to the underlying GetConfig method.
// It will increment the count of requests made to GetConfig.
func (c *CloudHSM) GetConfig(input *cloudhsm.GetConfigInput) (*cloudhsm.GetConfigOutput, error) {
	c.inc("GetConfig")
	return c.svc.GetConfig(input)
}

// GetConfigWithContext is a passthrough to the underlying GetConfigWithContext method.
// It will increment the count of requests made to GetConfig.
func (c *CloudHSM) GetConfigWithContext(ctx aws.Context, input *cloudhsm.GetConfigInput, opts ...request.Option) (*cloudhsm.GetConfigOutput, error) {
	c.inc("GetConfig")
	return c.svc.GetConfigWithContext(ctx, input, opts...)
}

// ListAvailableZonesRequest is a passthrough to the underlying ListAvailableZonesRequest.
// It will increment the count of requests made to ListAvailableZones.
func (c *CloudHSM) ListAvailableZonesRequest(input *cloudhsm.ListAvailableZonesInput) (req *request.Request, output *cloudhsm.ListAvailableZonesOutput) {
	c.inc("ListAvailableZones")
	return c.svc.ListAvailableZonesRequest(input)
}

// ListAvailableZones is a passthrough to the underlying ListAvailableZones method.
// It will increment the count of requests made to ListAvailableZones.
func (c *CloudHSM) ListAvailableZones(input *cloudhsm.ListAvailableZonesInput) (*cloudhsm.ListAvailableZonesOutput, error) {
	c.inc("ListAvailableZones")
	return c.svc.ListAvailableZones(input)
}

// ListAvailableZonesWithContext is a passthrough to the underlying ListAvailableZonesWithContext method.
// It will increment the count of requests made to ListAvailableZones.
func (c *CloudHSM) ListAvailableZonesWithContext(ctx aws.Context, input *cloudhsm.ListAvailableZonesInput, opts ...request.Option) (*cloudhsm.ListAvailableZonesOutput, error) {
	c.inc("ListAvailableZones")
	return c.svc.ListAvailableZonesWithContext(ctx, input, opts...)
}

// ListHapgsRequest is a passthrough to the underlying ListHapgsRequest.
// It will increment the count of requests made to ListHapgs.
func (c *CloudHSM) ListHapgsRequest(input *cloudhsm.ListHapgsInput) (req *request.Request, output *cloudhsm.ListHapgsOutput) {
	c.inc("ListHapgs")
	return c.svc.ListHapgsRequest(input)
}

// ListHapgs is a passthrough to the underlying ListHapgs method.
// It will increment the count of requests made to ListHapgs.
func (c *CloudHSM) ListHapgs(input *cloudhsm.ListHapgsInput) (*cloudhsm.ListHapgsOutput, error) {
	c.inc("ListHapgs")
	return c.svc.ListHapgs(input)
}

// ListHapgsWithContext is a passthrough to the underlying ListHapgsWithContext method.
// It will increment the count of requests made to ListHapgs.
func (c *CloudHSM) ListHapgsWithContext(ctx aws.Context, input *cloudhsm.ListHapgsInput, opts ...request.Option) (*cloudhsm.ListHapgsOutput, error) {
	c.inc("ListHapgs")
	return c.svc.ListHapgsWithContext(ctx, input, opts...)
}

// ListHsmsRequest is a passthrough to the underlying ListHsmsRequest.
// It will increment the count of requests made to ListHsms.
func (c *CloudHSM) ListHsmsRequest(input *cloudhsm.ListHsmsInput) (req *request.Request, output *cloudhsm.ListHsmsOutput) {
	c.inc("ListHsms")
	return c.svc.ListHsmsRequest(input)
}

// ListHsms is a passthrough to the underlying ListHsms method.
// It will increment the count of requests made to ListHsms.
func (c *CloudHSM) ListHsms(input *cloudhsm.ListHsmsInput) (*cloudhsm.ListHsmsOutput, error) {
	c.inc("ListHsms")
	return c.svc.ListHsms(input)
}

// ListHsmsWithContext is a passthrough to the underlying ListHsmsWithContext method.
// It will increment the count of requests made to ListHsms.
func (c *CloudHSM) ListHsmsWithContext(ctx aws.Context, input *cloudhsm.ListHsmsInput, opts ...request.Option) (*cloudhsm.ListHsmsOutput, error) {
	c.inc("ListHsms")
	return c.svc.ListHsmsWithContext(ctx, input, opts...)
}

// ListLunaClientsRequest is a passthrough to the underlying ListLunaClientsRequest.
// It will increment the count of requests made to ListLunaClients.
func (c *CloudHSM) ListLunaClientsRequest(input *cloudhsm.ListLunaClientsInput) (req *request.Request, output *cloudhsm.ListLunaClientsOutput) {
	c.inc("ListLunaClients")
	return c.svc.ListLunaClientsRequest(input)
}

// ListLunaClients is a passthrough to the underlying ListLunaClients method.
// It will increment the count of requests made to ListLunaClients.
func (c *CloudHSM) ListLunaClients(input *cloudhsm.ListLunaClientsInput) (*cloudhsm.ListLunaClientsOutput, error) {
	c.inc("ListLunaClients")
	return c.svc.ListLunaClients(input)
}

// ListLunaClientsWithContext is a passthrough to the underlying ListLunaClientsWithContext method.
// It will increment the count of requests made to ListLunaClients.
func (c *CloudHSM) ListLunaClientsWithContext(ctx aws.Context, input *cloudhsm.ListLunaClientsInput, opts ...request.Option) (*cloudhsm.ListLunaClientsOutput, error) {
	c.inc("ListLunaClients")
	return c.svc.ListLunaClientsWithContext(ctx, input, opts...)
}

// ListTagsForResourceRequest is a passthrough to the underlying ListTagsForResourceRequest.
// It will increment the count of requests made to ListTagsForResource.
func (c *CloudHSM) ListTagsForResourceRequest(input *cloudhsm.ListTagsForResourceInput) (req *request.Request, output *cloudhsm.ListTagsForResourceOutput) {
	c.inc("ListTagsForResource")
	return c.svc.ListTagsForResourceRequest(input)
}

// ListTagsForResource is a passthrough to the underlying ListTagsForResource method.
// It will increment the count of requests made to ListTagsForResource.
func (c *CloudHSM) ListTagsForResource(input *cloudhsm.ListTagsForResourceInput) (*cloudhsm.ListTagsForResourceOutput, error) {
	c.inc("ListTagsForResource")
	return c.svc.ListTagsForResource(input)
}

// ListTagsForResourceWithContext is a passthrough to the underlying ListTagsForResourceWithContext method.
// It will increment the count of requests made to ListTagsForResource.
func (c *CloudHSM) ListTagsForResourceWithContext(ctx aws.Context, input *cloudhsm.ListTagsForResourceInput, opts ...request.Option) (*cloudhsm.ListTagsForResourceOutput, error) {
	c.inc("ListTagsForResource")
	return c.svc.ListTagsForResourceWithContext(ctx, input, opts...)
}

// ModifyHapgRequest is a passthrough to the underlying ModifyHapgRequest.
// It will increment the count of requests made to ModifyHapg.
func (c *CloudHSM) ModifyHapgRequest(input *cloudhsm.ModifyHapgInput) (req *request.Request, output *cloudhsm.ModifyHapgOutput) {
	c.inc("ModifyHapg")
	return c.svc.ModifyHapgRequest(input)
}

// ModifyHapg is a passthrough to the underlying ModifyHapg method.
// It will increment the count of requests made to ModifyHapg.
func (c *CloudHSM) ModifyHapg(input *cloudhsm.ModifyHapgInput) (*cloudhsm.ModifyHapgOutput, error) {
	c.inc("ModifyHapg")
	return c.svc.ModifyHapg(input)
}

// ModifyHapgWithContext is a passthrough to the underlying ModifyHapgWithContext method.
// It will increment the count of requests made to ModifyHapg.
func (c *CloudHSM) ModifyHapgWithContext(ctx aws.Context, input *cloudhsm.ModifyHapgInput, opts ...request.Option) (*cloudhsm.ModifyHapgOutput, error) {
	c.inc("ModifyHapg")
	return c.svc.ModifyHapgWithContext(ctx, input, opts...)
}

// ModifyHsmRequest is a passthrough to the underlying ModifyHsmRequest.
// It will increment the count of requests made to ModifyHsm.
func (c *CloudHSM) ModifyHsmRequest(input *cloudhsm.ModifyHsmInput) (req *request.Request, output *cloudhsm.ModifyHsmOutput) {
	c.inc("ModifyHsm")
	return c.svc.ModifyHsmRequest(input)
}

// ModifyHsm is a passthrough to the underlying ModifyHsm method.
// It will increment the count of requests made to ModifyHsm.
func (c *CloudHSM) ModifyHsm(input *cloudhsm.ModifyHsmInput) (*cloudhsm.ModifyHsmOutput, error) {
	c.inc("ModifyHsm")
	return c.svc.ModifyHsm(input)
}

// ModifyHsmWithContext is a passthrough to the underlying ModifyHsmWithContext method.
// It will increment the count of requests made to ModifyHsm.
func (c *CloudHSM) ModifyHsmWithContext(ctx aws.Context, input *cloudhsm.ModifyHsmInput, opts ...request.Option) (*cloudhsm.ModifyHsmOutput, error) {
	c.inc("ModifyHsm")
	return c.svc.ModifyHsmWithContext(ctx, input, opts...)
}

// ModifyLunaClientRequest is a passthrough to the underlying ModifyLunaClientRequest.
// It will increment the count of requests made to ModifyLunaClient.
func (c *CloudHSM) ModifyLunaClientRequest(input *cloudhsm.ModifyLunaClientInput) (req *request.Request, output *cloudhsm.ModifyLunaClientOutput) {
	c.inc("ModifyLunaClient")
	return c.svc.ModifyLunaClientRequest(input)
}

// ModifyLunaClient is a passthrough to the underlying ModifyLunaClient method.
// It will increment the count of requests made to ModifyLunaClient.
func (c *CloudHSM) ModifyLunaClient(input *cloudhsm.ModifyLunaClientInput) (*cloudhsm.ModifyLunaClientOutput, error) {
	c.inc("ModifyLunaClient")
	return c.svc.ModifyLunaClient(input)
}

// ModifyLunaClientWithContext is a passthrough to the underlying ModifyLunaClientWithContext method.
// It will increment the count of requests made to ModifyLunaClient.
func (c *CloudHSM) ModifyLunaClientWithContext(ctx aws.Context, input *cloudhsm.ModifyLunaClientInput, opts ...request.Option) (*cloudhsm.ModifyLunaClientOutput, error) {
	c.inc("ModifyLunaClient")
	return c.svc.ModifyLunaClientWithContext(ctx, input, opts...)
}

// RemoveTagsFromResourceRequest is a passthrough to the underlying RemoveTagsFromResourceRequest.
// It will increment the count of requests made to RemoveTagsFromResource.
func (c *CloudHSM) RemoveTagsFromResourceRequest(input *cloudhsm.RemoveTagsFromResourceInput) (req *request.Request, output *cloudhsm.RemoveTagsFromResourceOutput) {
	c.inc("RemoveTagsFromResource")
	return c.svc.RemoveTagsFromResourceRequest(input)
}

// RemoveTagsFromResource is a passthrough to the underlying RemoveTagsFromResource method.
// It will increment the count of requests made to RemoveTagsFromResource.
func (c *CloudHSM) RemoveTagsFromResource(input *cloudhsm.RemoveTagsFromResourceInput) (*cloudhsm.RemoveTagsFromResourceOutput, error) {
	c.inc("RemoveTagsFromResource")
	return c.svc.RemoveTagsFromResource(input)
}

// RemoveTagsFromResourceWithContext is a passthrough to the underlying RemoveTagsFromResourceWithContext method.
// It will increment the count of requests made to RemoveTagsFromResource.
func (c *CloudHSM) RemoveTagsFromResourceWithContext(ctx aws.Context, input *cloudhsm.RemoveTagsFromResourceInput, opts ...request.Option) (*cloudhsm.RemoveTagsFromResourceOutput, error) {
	c.inc("RemoveTagsFromResource")
	return c.svc.RemoveTagsFromResourceWithContext(ctx, input, opts...)
}
