// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package kinesisvideoarchivedmediacounter

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/kinesisvideoarchivedmedia"
)

// GetMediaForFragmentListRequest is a passthrough to the underlying GetMediaForFragmentListRequest.
// It will increment the count of requests made to GetMediaForFragmentList.
func (c *KinesisVideoArchivedMedia) GetMediaForFragmentListRequest(input *kinesisvideoarchivedmedia.GetMediaForFragmentListInput) (req *request.Request, output *kinesisvideoarchivedmedia.GetMediaForFragmentListOutput) {
	c.inc("GetMediaForFragmentList")
	return c.svc.GetMediaForFragmentListRequest(input)
}

// GetMediaForFragmentList is a passthrough to the underlying GetMediaForFragmentList method.
// It will increment the count of requests made to GetMediaForFragmentList.
func (c *KinesisVideoArchivedMedia) GetMediaForFragmentList(input *kinesisvideoarchivedmedia.GetMediaForFragmentListInput) (*kinesisvideoarchivedmedia.GetMediaForFragmentListOutput, error) {
	c.inc("GetMediaForFragmentList")
	return c.svc.GetMediaForFragmentList(input)
}

// GetMediaForFragmentListWithContext is a passthrough to the underlying GetMediaForFragmentListWithContext method.
// It will increment the count of requests made to GetMediaForFragmentList.
func (c *KinesisVideoArchivedMedia) GetMediaForFragmentListWithContext(ctx aws.Context, input *kinesisvideoarchivedmedia.GetMediaForFragmentListInput, opts ...request.Option) (*kinesisvideoarchivedmedia.GetMediaForFragmentListOutput, error) {
	c.inc("GetMediaForFragmentList")
	return c.svc.GetMediaForFragmentListWithContext(ctx, input, opts...)
}

// ListFragmentsRequest is a passthrough to the underlying ListFragmentsRequest.
// It will increment the count of requests made to ListFragments.
func (c *KinesisVideoArchivedMedia) ListFragmentsRequest(input *kinesisvideoarchivedmedia.ListFragmentsInput) (req *request.Request, output *kinesisvideoarchivedmedia.ListFragmentsOutput) {
	c.inc("ListFragments")
	return c.svc.ListFragmentsRequest(input)
}

// ListFragments is a passthrough to the underlying ListFragments method.
// It will increment the count of requests made to ListFragments.
func (c *KinesisVideoArchivedMedia) ListFragments(input *kinesisvideoarchivedmedia.ListFragmentsInput) (*kinesisvideoarchivedmedia.ListFragmentsOutput, error) {
	c.inc("ListFragments")
	return c.svc.ListFragments(input)
}

// ListFragmentsWithContext is a passthrough to the underlying ListFragmentsWithContext method.
// It will increment the count of requests made to ListFragments.
func (c *KinesisVideoArchivedMedia) ListFragmentsWithContext(ctx aws.Context, input *kinesisvideoarchivedmedia.ListFragmentsInput, opts ...request.Option) (*kinesisvideoarchivedmedia.ListFragmentsOutput, error) {
	c.inc("ListFragments")
	return c.svc.ListFragmentsWithContext(ctx, input, opts...)
}
